Only warn if changed modules fail to build.
Signed-off-by: Andrew Symington <simmers@google.com>

diff --git a/.github/workflows/_check_distribution_compiles.yml b/.github/workflows/_check_distribution_compiles.yml
--- a/.github/workflows/_check_distribution_compiles.yml
+++ b/.github/workflows/_check_distribution_compiles.yml
@@ -124,7 +124,9 @@ jobs:
           fi
         done
         if [ -n "$TARGETS" ]; then
-          bazel build --config ci $TARGETS 2>&1 | tee build_changed_packages.log
+          if ! bazel build --config ci $TARGETS 2>&1 | tee build_changed_packages.log; then
+            echo "::warning title=Build changed packages failed::Building changed packages ($TARGETS) failed, but will not block CI as some modules may be outside the supported collection."
+          fi
         fi
 
     # Build the ros 2 distribution
