When a package change fails testing, warn don't fail.
Signed-off-by: Andrew Symington <simmers@google.com>

diff --git a/.github/workflows/_check_distribution_tests.yml b/.github/workflows/_check_distribution_tests.yml
--- a/.github/workflows/_check_distribution_tests.yml
+++ b/.github/workflows/_check_distribution_tests.yml
@@ -168,15 +168,16 @@ jobs:
             fi
           done
           if [ -n "$TARGETS" ]; then
-            bazel build --config ci --build_tests_only $TARGETS
-            bazel test --config ci --test_env=RMW_IMPLEMENTATION=${{ inputs.rmw }} $TARGETS 2>&1 | tee ${{ inputs.rmw }}.changed_packages.test.log || {
-              rc=$?
+            if ! bazel build --config ci --build_tests_only $TARGETS 2>&1 | tee ${{ inputs.rmw }}.changed_packages.build.log; then
+              echo "::warning title=Build changed packages failed::Building changed packages ($TARGETS) tests failed, but will not block CI as some modules may be outside the supported collection."
+            elif ! bazel test --config ci --test_env=RMW_IMPLEMENTATION=${{ inputs.rmw }} $TARGETS 2>&1 | tee ${{ inputs.rmw }}.changed_packages.test.log; then
+              rc=${PIPESTATUS[0]}
               # Bazel exits with 4 when no test targets match the pattern,
               # which is expected for packages that don't declare any tests.
               if [ "$rc" -ne 4 ]; then
-                test_status=$rc
+                echo "::warning title=Test changed packages failed::Testing changed packages ($TARGETS) failed, but will not block CI as some modules may be outside the supported collection."
               fi
-            }
+            fi
           fi
         fi
 
